# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d1718c455e2774f716a4d096ba6e799b9aa596898179594a96256dd5e0f74e86908a363e9203cd09f8b3e336b68fa8eeab6a6e9e20b6d42cfe067c1ab49eb42

test:
  secret_key_base: 8fd710d64206007ed485586260d808aa22ccd3b97ce643a72f6a0dbc107c2d80cc6abedf818f6444c7fc9d0d0fc63594ad9454262715e68956b91bc276058ac5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
